build(homefront): set up playwright for frontend NextJS
nashtech-garage/nodejs-msa pull request #105
Opened 2023-06-05 15:40 UTC by hungxnguyen118

Set Up Playwright platform testing for NextJS (home front)

2023-06-06 09:10 UTC, panoti requested changes
Hi a @hungxnguyen118 , I've just leaved some comment for you. If you have any question, please feel free to discuss. Thank you so much

2023-06-06 09:10 UTC, panoti commented on homefront/package-lock.json
you can discard this file because we don't change `package.json`

2023-06-06 09:10 UTC, panoti commented on homefront/tests-examples/demo-todo-app.spec.ts
we don't need commit this file to the repo you can keep it at local pc for reference.

2023-06-06 09:10 UTC, panoti commented on homefront/app/page.tsx
We may be able to replace this file with the new UI, so we don't make this file changed as well.

2023-06-06 09:10 UTC, panoti commented on homefront/tests/home.spec.ts
I've inserted an example test for index page, so you can remove this file as well.

2023-06-07 02:52 UTC, hungxnguyen118 commented on homefront/package-lock.json
we already change this file. Just on github don't show difference. So you must click into "load diff" button will show like this
![image](https://github.com/nashtech-garage/nodejs-msa/assets/44957422/c7e12eca-b1bd-4246-9dfa-ecdfd6c14049)

2023-06-07 02:52 UTC, hungxnguyen118 commented on homefront/tests-examples/demo-todo-app.spec.ts
ok Mr. Thanh. I will remove it.

2023-06-07 02:53 UTC, hungxnguyen118 commented on homefront/tests/home.spec.ts
ok Mr. Thanh. I will remove it too :)

2023-06-07 02:54 UTC, hungxnguyen118 commented on homefront/app/page.tsx
ok Mr. Thanh. I will remove this and modified the spec test file for about page. Because this spec test is need click into button About Us Page. So I will change test case to direct url request

2023-06-07 04:27 UTC, panoti commented on homefront/package-lock.json
Hmm, I think I found the root cause here. I use `pnpm` for package management.

2023-06-07 04:28 UTC, panoti approved these changes

2023-06-07 04:28 UTC, merged