Mobile - Authentication screens
nashtech-garage/nodejs-msa pull request #165
Opened 2024-09-17 05:39 UTC by emhat098

- Convert the authentication wireframe to a Flutter UI.

Note: This is UI only; the global state setup or backend integration for completing the full authentication workflow in the mobile app will be done later.

2024-09-17 06:26 UTC, panoti requested changes
avoid push dist/build/cache files to git. You can use gitignore to skip commit these files

2024-09-17 07:00 UTC, tuonglevan submitted a review, later dismissed
LGTM

2024-09-18 15:03 UTC, panoti commented on .DS_Store
Can we ignore .DS_Store due to MacOS?

2024-09-19 04:34 UTC, emhat098 commented on .DS_Store
I updated the code change. Could you please review the code change?

2024-09-19 04:59 UTC, panoti approved these changes
LGTM

2024-09-19 06:28 UTC, merged